plugins:
  duplication:
    enabled: true
checks:
  Similar code:
    enabled: false
config:
  languages:
    - javascript
fixme:
  enabled: true
ratings:
  paths:
    - "server/*.js"
    - "server/**/*.js"
    - "server/tests/**/*.js"
exclude_patterns:
  - node_modules/
  - server/dummyData/
  - UI/