language: node_js
env:
  global:
    - CC_TEST_REPORTER_ID=ccb0b742510740eb72d6e6e686b6873192a63ea832e9370ce9ad6bbff9ad2e4e
node_js:
 - "8.12.0"
before_install:
  - npm i -g npm@6.4.1
before_script:
  - yarn global add nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - npm test
 - npm run coveralls
 - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
